//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class barcode
    {
        [Display(Name ="ID")]
        [Required]
        public int Bid { get; set; }
        [Display(Name = "Invoice Number")]
        [Required]
        public int Bcode { get; set; }
    }
}
