//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.orderlist_pw = new HashSet<orderlist_pw>();
        }
        [Display(Name = "ID")]
        [Required]
        public int Cid { get; set; }
        [Display(Name = "Full Name")]
        [Required]
        public string Cfn { get; set; }
        [Display(Name = "Contact")]
        [Required]
        public string Ccontact { get; set; }
        [Display(Name = "Email ID")]
        [Required]
        public string Cemail { get; set; }
        [Display(Name = "Address")]
        [Required]
        public string Caddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderlist_pw> orderlist_pw { get; set; }
    }
}
