//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lmsEntities : DbContext
    {
        public lmsEntities()
            : base("name=lmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<priceList_pkw> priceList_pkw { get; set; }
        public virtual DbSet<priceList_pw> priceList_pw { get; set; }
        public virtual DbSet<priceList_ww> priceList_ww { get; set; }
        public virtual DbSet<barcode> barcodes { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<orderlist_pw> orderlist_pw { get; set; }
        public virtual DbSet<orderlist_pkw> orderlist_pkw { get; set; }
        public virtual DbSet<orderlist_ww> orderlist_ww { get; set; }
        public virtual DbSet<delstatu> delstatus { get; set; }
    }
}
