//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class orderlist_pkw
    {
        [Display(Name = "Invoice No")]
        [Required]
        public int OPWid { get; set; }
        [Display(Name = "Customer")]
        [Required]
        public string OPWcust { get; set; }
        [Display(Name = "Item Code")]
        [Required]
        public string OPWcode { get; set; }
        [Display(Name = "Service")]
        [Required]
        public string OPWservice { get; set; }
        [Display(Name = "Fixed Piece(Month)")]
        [Required]
        public int OPWfp { get; set; }
        [Display(Name = "Order Date")]
        [Required]
        public System.DateTime OPWdate { get; set; }
        [Display(Name = "Delivery Date")]
        [Required]
        public System.DateTime OPWdel { get; set; }
        [Display(Name = "Status")]
        [Required]
        public string OPWstat { get; set; }
        [Display(Name = "Advance Payment")]
        [Required]
        public decimal OPWadvance { get; set; }
        [Display(Name = "Due Payment")]
        [Required]
        public Nullable<decimal> OPWdue { get; set; }
        [Display(Name = "Total Amount")]
        [Required]
        public decimal OPWprice { get; set; }
    }
}
