//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class priceList_pw
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public priceList_pw()
        {
            this.orderlist_pw = new HashSet<orderlist_pw>();
        }
        [Display(Name = "ID")]
        [Required]
        public int PWid { get; set; }
        [Display(Name = "Item Code")]
        [Required]
        public string PWcode { get; set; }
        [Display(Name = "Service")]
        [Required]
        public string PWservice { get; set; }
        [Display(Name = "Cloth Type")]
        [Required]
        public string PWclothtype { get; set; }
        [Display(Name = "Total Amount")]
        [Required]
        public decimal PWprice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderlist_pw> orderlist_pw { get; set; }
    }
}
