//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class priceList_pkw
    {
        [Display(Name = "ID")]
        [Required]
        public int PKWid { get; set; }
        [Display(Name = "Item Code")]
        [Required]
        public string PKWcode { get; set; }
        [Display(Name = "Service")]
        [Required]
        public string PKWservice { get; set; }
        [Display(Name = "Fixed Piece Montly")]
        [Required]
        public int PKWmonthpiece { get; set; }
        [Display(Name = "Total Amount")]
        [Required]
        public decimal PKWprice { get; set; }
    }
}
